### PR TITLE
update nan to 2.0.x to support iojs 3.0

### PR DESCRIPTION
**Pull request by XadillaX**
Nan 1.9.x not support iojs 3.0.

So I updated nan to 2.0.x and modified some `*.cc` code.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Pulled #35 instead.

**Comment by 3rd-Eden** [comment]
But thanks for your contribution <3

**Comment by XadillaX** [comment]
but that pr dropped c++ addon, will it be ok?

**Comment by 3rd-Eden** [comment]
There's a pretty intensive distribution test: https://github.com/3rd-Eden/node-hashring/blob/master/tests/distribution.test.js which compares the output of this module against the output of ketema and the HashRing library. The output is still identical after merging the pull request so there is no change in the distribution of the hashring.

**Comment by XadillaX** [comment]
i mean something like benchmark?

**Comment by 3rd-Eden** [comment]
There's no benchmark as far as I'm aware of, sorry.

**Comment by 3rd-Eden** [comment]
But it would be fairly easy to generate of course as both versions are now in npm.

**Pull request closed without merging**
